# Generated by Django 5.1.4 on 2024-12-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_alter_alumni_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='rv_email',
        ),
    ]
