# Generated by Django 5.1.4 on 2024-12-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_remove_category_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AlterField(
            model_name='higherstudies',
            name='specialization',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning'), ('Cloud Computing', 'Cloud Computing'), ('Data Science', 'Data Science'), ('Computer Vision', 'Computer Vision'), ('Natural Language processing', 'Natural Language processing'), ('Marketing', 'Marketing'), ('Finance Systems', 'Finanace Systems'), ('IOT', 'IOT'), ('others', 'others')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='Category',
            field=models.CharField(choices=[('Enterprenuer', 'Enterprenuer'), ('Higher Studies', 'Higher Studies'), ('Job', 'Job'), ('Others', 'Others')], default='Job', max_length=20),
        ),
    ]
